version: '3'
services:
  devinhousepostgres:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devinhouse
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432